version: "3"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_service
    ports:
      - "${API_PORT}:${API_PORT}"
    links:
      - db
    volumes:
      - ./api:/usr/src/app
    networks:
      - app_network
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_DIALECT=${DB_DIALECT}
      - DB_PORT=${DB_PORT}

  # app:
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile
  #   container_name: app_service
  #   ports:
  #     - "${FLUTTER_PORT}:${FLUTTER_PORT}"
  #   links:
  #     - api
  #   volumes:
  #     - ./app:/usr/src/app
  #   networks:
  #     - app_network
  #   environment:
  #     - API_URL=${API_URL}
  #     - FLUTTER_PORT=${FLUTTER_PORT}
  #     - API_KEY=${API_KEY}
  #     - APP_ID=${APP_ID}
  #     - MESSAGING_SENDER_ID=${MESSAGING_SENDER_ID}
  #     - STORAGE_BUCKET=${STORAGE_BUCKET}
  #     - PROJECT_ID=${PROJECT_ID}

  db:
    image: postgres:15
    container_name: database_service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
