name: app
description: "A new Flutter Biology Research App project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.2.1
  fluttertoast: ^8.2.8
  flutter_native_splash: ^2.2.19

  cupertino_icons: ^1.0.8
  lottie: ^3.1.3
  google_fonts: ^6.2.1

  http: ^1.2.2
  animated_text_kit: ^4.2.2
  smooth_page_indicator: ^1.0.1
  bulleted_list: ^0.0.1+0.1a
  blur: ^4.0.0
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  get: ^4.6.5
  intl: ^0.19.0
  table_calendar: ^3.0.8

  provider: ^6.1.2
  shared_preferences: ^2.3.3

  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:
  color: "#116530"
  image: assets/foodicon.png
  android_12:
    color: "#116530"
    image: assets/foodicon.png
  android: true
  ios: true
